### ISSUE TITLE
Build on Debian

### ISSUE THREAD

**Issue by BlauerHunger** [moz-plasma/firefox-plasma-support#17]
I use Plasma 5.8.2 on Debian Unstable with Firefox, and I'd like to use your packages on Debian, too. So please provide either a list with the extra things I need to build and a README file where I can find instructions on how to build it on Debian and where I have to pay extra attention or directly provide Debian packages, either in a seperate repo or submitted for the Debian repos.

**Comment by llelectronics** [comment]
We provid packages build against debian stable on dci. Here dci.pangea.pub/view/Plasmazilla

**Comment by BlauerHunger** [comment]
What do I need on Debian Unstable to get all the features of what I get on Ubuntu with Plasma 5.8 when I add the PPA and install firefox-plasma and mozilla-kde-support?

**Comment by llelectronics** [comment]
That should be enough

**Comment by shadeslayer** [comment]
Debian unstable is unsupported, however you can read the code [here](https://github.com/blue-systems/pangea-tooling/blob/master/ci-tooling/lib/kdeify.rb#L55) to see what we do to the firefox package
