### ISSUE TITLE
Add support for Ubuntu 18.04 LTS (Bionic Beaver) in plasmazilla PPA

### ISSUE THREAD

**Issue by MurzNN** [moz-plasma/firefox-plasma-support#34]
Ubuntu 18.04 is released, but there are still missing Bionic category in https://launchpad.net/~plasmazilla/+archive/ubuntu/releases PPA. Did you plan to add support for Ubuntu Bionic Beaver in plasmazilla ppa?

**Comment by llelectronics** [comment]
Good point. This is needed.

**Comment by MurzNN** [comment]
Firefox-plasma Ubuntu 18.04 version is added to ppa, thanks! Thinderbird-plasma is missed, but version for Ubuntu 16.04 installs and works well on Bionic.
