### ISSUE TITLE
Spellchecking no longer works in Firefox 62 - Ubuntu 18.04

### ISSUE THREAD

**Issue by Aboulafia666** [moz-plasma/firefox-plasma-support#36]
Firefox deb package : 1:62.0+build2-0ubuntu0.18.04.4
Arch : amd64
Distro : KDE Neon 18.04

Spellchecking is no longer available (for other languages than American English) in the latest Firefox 62 build.
I had to manually (re)create the config key in about:config
**spellchecker.dictionary_path**     string    **/usr/share/hunspell**
to make it work again.

**Comment by bruno666** [comment]
It seems to be fixed in latest Firefox package : 1:62.0.3+build1-0ubuntu0.18.04.2

**Comment by Aboulafia666** [comment]
It seems to be fixed in latest Firefox package : 1:62.0.3+build1-0ubuntu0.18.04.2
